name = "mycost"
compatibility_date = "2026-09-01"
pages_build_output_dir = "dist"

[vars]
APP_NAME = "MyCost"

[[d1_databases]]
binding = "DB"
database_name = "mycost"
database_id = "REPLACE_WITH_D1_DATABASE_ID"
